apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: matrix

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: conduwuit

images:
  - name: ghcr.io/girlbossceo/conduwuit
    newTag: "latest"

resources:
  - manifests/namespace.yml
  - manifests/ingress.yml
  - manifests/conduwuit.yml
  - manifests/element-web.yml

configMapGenerator:
  - name: conduwuit-config
    files:
      - "conduwuit.toml=config/conduwuit.toml"

  - name: element-web
    files:
      - "config.json=config/element-web.json"

generators:
  - ./secret-generator.yml

