apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nix-binary-cache

resources:
  - manifests/namespace.yml
  - manifests/attic.yml
  - manifests/ingress.yml

configMapGenerator:
  - name: attic-config
    files:
      - config.toml=config/attic-config.toml

generators:
  - ./secret-generator.yml
