apiVersion: batch/v1
kind: CronJob
metadata:
  name: firefly-cron
  labels: &labels
    app.kubernetes.io/name: firefly-cron
    app.kubernetes.io/component: maintenance-cron
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "@hourly"
  jobTemplate:
    spec: # spec of the job
      template: # pod template
        spec: # spec of the pod
          restartPolicy: Never
          volumes:
            - name: firefly-uploads
              persistentVolumeClaim:
                claimName: firefly-uploads
          containers:
            - name: firefly-cron
              image: docker.io/fireflyiii/core
              command: [ "/usr/local/bin/php" ]
              args: [ "/var/www/html/artisan", "firefly-iii:cron" ]
              envFrom:
                - configMapRef:
                    name: firefly-env
                - secretRef:
                    name: firefly-env
              volumeMounts:
                - name: firefly-uploads
                  mountPath: /var/www/html/storage/upload
                
