apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mailserver

resources:
  - manifests/namespace.yml

  # new mailserver
  - manifests/tls.yml
  - manifests/ingress.yml
  - manifests/mail-proxy.yml
  - manifests/dovecot.yml
  - manifests/unbound.yml
  - manifests/rspamd-redis.yml
  - manifests/rspamd.yml
  - manifests/postfix.yml

  # mailcalf resources
  - mailcalf-manifests/mailcalf-certificate.yml
  - mailcalf-manifests/mailcalf-deployment.yml
  - mailcalf-manifests/mailcalf-services.yml
  - mailcalf-manifests/mailcalf-storage.yml

images:
  - name: docker.io/dovecot/dovecot
    newTag: "2.4.4-dev"
  - name: docker.io/haproxy
    newTag: "3.4.3"
  - name: docker.io/rspamd/rspamd
    newTag: "latest"

configMapGenerator:
  - name: dovecot-configs
    files:
      - local.conf=configs/dovecot/local.conf
      - fts.conf=configs/dovecot/fts.conf
      - sieve.conf=configs/dovecot/sieve.conf
      - sasl.conf=configs/dovecot/sasl.conf

  - name: haproxy-config
    files:
      - haproxy.cfg=configs/haproxy.cfg

  - name: rspamd-configs
    files:
      - actions.conf=configs/rspamd/actions.conf
      - options.inc=configs/rspamd/options.inc
      - redis.conf=configs/rspamd/redis.conf
      - worker-proxy.inc=configs/rspamd/worker-proxy.inc
      - classifier-bayes.conf=configs/rspamd/classifier-bayes.conf
      - dkim_signing.conf=configs/rspamd/dkim_signing.conf

  - name: unbound-config
    files:
      - unbound.conf=configs/unbound.conf

  - name: postfix-configs
    files:
      - main.cf=configs/postfix/main.cf
      - master.cf=configs/postfix/master.cf
      - virtual_alias_maps.txt=configs/postfix/virtual_alias_maps.txt
      - virtual_mailbox_domains.txt=configs/postfix/virtual_mailbox_domains.txt
  
  # mailcalf
  - name: mailcalf-configs
    files:
      - dovecot_local.conf=mailcalf-configs/dovecot_local.conf
      - postfix_local.cf=mailcalf-configs/postfix_local.cf
      - postfix_virtual_alias_maps.txt=mailcalf-configs/postfix_virtual_alias_maps.txt
      - postfix_virtual_domains.txt=mailcalf-configs/postfix_virtual_domains.txt
      - postfix_sender_login_maps.txt=mailcalf-configs/postfix_sender_login_maps.txt
      - postfix_recipient_access.txt=mailcalf-configs/postfix_recipient_access.txt
      - rspamd_worker_controller.inc=mailcalf-configs/rspamd_worker_controller.inc
      - opendkim_domains.txt=mailcalf-configs/opendkim_domains.txt
      - dovecot-extra.passwd=mailcalf-configs/dovecot-extra.passwd

generators:
  - ./secret-generator.yml
