# ref: https://github.com/viaduct-ai/kustomize-sops
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
secretFrom:
  - metadata:
      name: dovecot-configs
      annotations:
        kustomize.config.k8s.io/needs-hash: "true"
    files:
      - dovecot-extra.passwd=configs/dovecot/dovecot-extra.secret.passwd
      - auth.conf=configs/dovecot/auth.secret.conf
      - rspamc.env=configs/dovecot/rspamc.secret.env     

  - metadata:
      name: rspamd-configs
      annotations:
        kustomize.config.k8s.io/needs-hash: "true"
    files:
      - worker-controller.inc=configs/rspamd/worker-controller.secret.inc
      - dkimkey.pem=configs/rspamd/dkimkey.secret.pem
  
  - metadata:
      name: mailcalf-configs
      annotations:
        kustomize.config.k8s.io/needs-hash: "true"
    files:
      - opendkim_key.pem=mailcalf-configs/dkim_key.secret.pem
      - dovecot-ldap.conf.ext=mailcalf-configs/ldap.secret.conf
      - fetchmailrc=mailcalf-configs/fetchmailrc.secret.txt
 
