keys:
  # Personal Keys
  - &lilly "age19h7xtfmt3py3ydgl8d8fgh8uakxqxjr74flrxev3pgmvvx94kvtq5d932d"
  # Functional Keys
  - &argocd "age1j2a8asttv66kkqk4008an46f4apjru9lgm0hxmvuuamlm5ts5f9qmzlx9y"
  # Per-Host Keys
  - &vpn-srv "age1gvt4lwamnuxmqgp5anhn008ze8kzrq287rn4jpn7k75fvn5ufvfsm73cvx"
  - &mail-srv "age1rhkf95d3ffm9jfw8pskxtaq30lk02awg8ag8nr76wtytemzzuszskxa5ch"
  - &hosting-srv "age1cqx8gxslaum3uk3weqdd6ur473mlsfvc6kt5l3pl9sdxpyg84azq0g7fqh"
  - &k8s-ctl-srv "age1ny4cv3stnnuvyf0qhhk7mha98rrhnwa4fpvdqt505qdsssn92flsayudjc"
  - &k8s-worker1-srv "age1ujymnlvetgl0kq7cpm9xsk4wuugdr869fynhawfe2gk4ucu2mycsd2yjta"
  - &k8s-worker2-srv "age13523e34ct38lf099wu5lag5f75j58tkee6f0ragzc40qqrxuqafs06alhd"
  - &k8s-ctl-aut-num "age14k696cxmqr34ll2ytaqjmtzr0qpjskppsh4a6gwxj99yspplx4ksyykjdx"
  - &k8s-worker1-aut-num "age1cwspvy0uatpkeyzpp08gh00pjekvek9lkp23rxk2fqhhh4k8vapszl4wn6"
  - &k8s-worker2-aut-num "age15eh366hrdz07ca4a3qzs8rtxr8nkhuj3fg3qvz94axyzf0zc8c9qgtare8"
  - &k8s-worker3-aut-num "age1k22c0uq675f5phyzevf36nj0yyvt3k97prxfz96m9xlec3rfhqjsvh5u0z"
  - &syncthing-aut-num "age1xz3g0du33t9mdyj33sj9n8hmc0fnmp8ec2lryawdcgldzuhfjd8s4u8wv5"
  - &webhost-aut-num "age1c54zwe67dwmw5swaf0qgzxtv49ryfczfyp2v5g42k5z66wzq55ksphx8fv"
  - &actions-runner-aut-num "age1ml0mt9d87lkjtj4pu27hn5hayz40zy05qam6u8524ck40r5f4ugqc9dme8"
  - &nas-myroot "age1gufa7z3leuufvps6wszfzyk7e8rqdpz3ryfneu9x4qfj0je95amq4gpd20"
  - &gtw-myroot "age186x5sfsv6txmtu8f9dfd84td6fq7cxup25nrtxlr43327xrqvpzsvqe6sv"
  - &home-proxy "age17jjjswxkjtlxcut4ddy9cj60fx35z396fde7a5g275xu6sle83usy6auta"
  - &rt-hosting "age1dlc688a6mm60vva8w4g0jfyjz3mx4sgjl65zewsrdjl0dgp025jsg5ac2g"
  - &priv-home-srv "age1nww3jxah80k2he6ur8gmzywx7hradf3cnyfshfzzd4rcp62kxsasw58phj"
  - &proxy-home "age17jjjswxkjtlxcut4ddy9cj60fx35z396fde7a5g275xu6sle83usy6auta"
  - &lillysLaptop "age1c3nxgz600s2pek704psnfns0vnz2jryyctlv6syrgs0n89jjyaksxtr5tx"
  - &lillysWorkLaptop "age1hn3ph2k4c37ndecy37zyvu4lhtk058xe7tkhnxdjry64wemcwc9q5s4ynp"
  - &lillysWorkstation "age1gu9536rsmf73ymqrnvv0emse85xwg22cdpy33jwfea395vt25spq67cdz2"

creation_rules:
  # Per-Host secrets
  - path_regex: "nix/data/host-secrets/vpn.srv.myroot.intern.yml"
    key_groups:
      - age: [ *lilly, *vpn-srv ]

  - path_regex: "nix/data/host-secrets/k8s-ctl.srv.myroot.intern.yml"
    key_groups:
      - age: [ *lilly, *k8s-ctl-srv ]

  - path_regex: "nix/data/host-secrets/hosting.srv.lly.sh.yml"
    key_groups:
      - age: [ *lilly, *hosting-srv ]

  - path_regex: "nix/data/host-secrets/nas.srv.myroot.intern.yml"
    key_groups:
      - age: [ *lilly, *nas-myroot ]

  - path_regex: "nix/data/host-secrets/gtw.srv.ftsell.de.yml"
    key_groups:
      - age: [ *lilly, *gtw-myroot ]

  - path_regex: "nix/data/host-secrets/proxy.srv.home.intern.yml"
    key_groups:
      - age: [ *lilly, *home-proxy ]

  - path_regex: "nix/data/host-secrets/priv.srv.home.intern.yml"
    key_groups:
      - age: [ *lilly, *priv-home-srv ]

  - path_regex: "nix/data/host-secrets/k8s-ctl.z9.aut-num.de.yml"
    key_groups:
      - age: [ *lilly, *k8s-ctl-aut-num ]

  - path_regex: "nix/data/host-secrets/syncthing.z9.aut-num.de.yml"
    key_groups:
      - age: [ *lilly, *syncthing-aut-num ]

  - path_regex: "nix/data/host-secrets/webhost.z9.aut-num.de.yml"
    key_groups:
      - age: [ *lilly, *webhost-aut-num ]

  - path_regex: "nix/data/host-secrets/actions-runner.z9.aut-num.de.yml"
    key_groups:
      - age: [ *lilly, *actions-runner-aut-num ]

  - path_regex: "nix/data/host-secrets/lillysLaptop.yml"
    key_groups:
      - age: [ *lilly, *lillysLaptop ]

  - path_regex: "nix/data/host-secrets/lillysWorkLaptop.yml"
    key_groups:
      - age: [ *lilly, *lillysWorkLaptop ]

  - path_regex: "nix/data/host-secrets/lillysWorkstation.yml"
    key_groups:
      - age: [ *lilly, *lillysWorkstation ]

  # Shared Secrets
  - path_regex: "nix/data/shared-secrets/mail_relay.yml"
    key_groups:
      - age:
          - *lilly
          - *vpn-srv
          - *gtw-myroot
          - *k8s-ctl-srv
          - *nas-myroot
          - *k8s-worker1-srv
          - *k8s-worker2-srv
          - *rt-hosting
          - *hosting-srv
          - *priv-home-srv
          - *proxy-home

  - path_regex: "nix/data/shared-secrets/k8s-node.yml"
    key_groups:
      - age: [ *lilly, *k8s-ctl-srv, *k8s-worker1-srv, *k8s-worker2-srv, *mail-srv ]

  - path_regex: "nix/data/shared-secrets/aut-sys-k8s.yml"
    key_groups:
      - age: [ *lilly, *k8s-ctl-aut-num, *k8s-worker1-aut-num, *k8s-worker2-aut-num, *k8s-worker3-aut-num ]

  - path_regex: "nix/data/shared-secrets/backup.yml"
    key_groups:
      - age: [ *lilly, *lillysLaptop, *lillysWorkstation, *nas-myroot, *priv-home-srv ]

  - path_regex: "nix/data/shared-secrets/task-sync.yml"
    key_groups:
      - age: [ *lilly, *lillysLaptop, *lillysWorkstation ]

  # generic secrets
  - path_regex: "nix/data/(.+-)?secrets/.+.yml"
    key_groups:
      - age: [ *lilly ]
  - path_regex: "nix/dotfiles/.+\\.secret\\..+"
    key_groups:
      - age: [ *lilly ]

  # Kubernetes secrets
  - path_regex: "k8s/.+\\.secret\\..+"
    key_groups:
      - age: [ *lilly, *argocd ]

  # specific files
  - path_regex: "nix/dotfiles/lilly/kubectl/config.secret.yml"
    encrypted_regex: "^(client-key-data)$"
    key_groups:
      - age: [ *lilly, *lillysLaptop, *lillysWorkstation ]
