keys:
  - &lilly "age19h7xtfmt3py3ydgl8d8fgh8uakxqxjr74flrxev3pgmvvx94kvtq5d932d"
  - &vpn-srv "age1gvt4lwamnuxmqgp5anhn008ze8kzrq287rn4jpn7k75fvn5ufvfsm73cvx"
  - &mail-srv "age1rhkf95d3ffm9jfw8pskxtaq30lk02awg8ag8nr76wtytemzzuszskxa5ch"
  - &hosting-srv "age1cqx8gxslaum3uk3weqdd6ur473mlsfvc6kt5l3pl9sdxpyg84azq0g7fqh"
  - &k8s-ctl-srv "age1ny4cv3stnnuvyf0qhhk7mha98rrhnwa4fpvdqt505qdsssn92flsayudjc"
  - &k8s-worker1-srv "age1ujymnlvetgl0kq7cpm9xsk4wuugdr869fynhawfe2gk4ucu2mycsd2yjta"
  - &k8s-worker2-srv "age13523e34ct38lf099wu5lag5f75j58tkee6f0ragzc40qqrxuqafs06alhd"
  - &nas-myroot "age1gufa7z3leuufvps6wszfzyk7e8rqdpz3ryfneu9x4qfj0je95amq4gpd20"
  - &gtw-myroot "age186x5sfsv6txmtu8f9dfd84td6fq7cxup25nrtxlr43327xrqvpzsvqe6sv"
  - &home-proxy "age17jjjswxkjtlxcut4ddy9cj60fx35z396fde7a5g275xu6sle83usy6auta"
  - &rt-hosting "age1dlc688a6mm60vva8w4g0jfyjz3mx4sgjl65zewsrdjl0dgp025jsg5ac2g"
  - &priv-home-srv "age1nww3jxah80k2he6ur8gmzywx7hradf3cnyfshfzzd4rcp62kxsasw58phj"
  - &proxy-home "age17jjjswxkjtlxcut4ddy9cj60fx35z396fde7a5g275xu6sle83usy6auta"
creation_rules:
  # per-host secrets
  - path_regex: "nix/data/secrets/vpn.srv.myroot.intern.yml"
    key_groups:
      - age: [ *lilly, *vpn-srv ]

  - path_regex: "nix/data/secrets/k8s.yml"
    key_groups:
      - age: [ *lilly, *k8s-ctl-srv, *k8s-worker1-srv, *k8s-worker2-srv, *mail-srv ]

  - path_regex: "nix/data/secrets/hosting.srv.lly.sh.yml"
    key_groups:
      - age: [ *lilly, *hosting-srv ]

  - path_regex: "nix/data/secrets/nas.srv.myroot.intern.yml"
    key_groups:
      - age: [ *lilly, *nas-myroot ]

  - path_regex: "nix/data/secrets/gtw.srv.ftsell.de.yml"
    key_groups:
      - age: [ *lilly, *gtw-myroot ]

  - path_regex: "nix/data/secrets/proxy.srv.home.intern.yml"
    key_groups:
      - age: [ *lilly, *home-proxy ]

  - path_regex: "nix/data/secrets/priv.srv.home.intern.yml"
    key_groups:
      - age: [ *lilly, *priv-home-srv ]

  # shared secrets
  - path_regex: "nix/data/secrets/mail_relay.yml"
    key_groups:
      - age:
          - *lilly
          - *vpn-srv
          - *gtw-myroot
          - *k8s-ctl-srv
          - *nas-myroot
          - *k8s-worker1-srv
          - *k8s-worker2-srv
          - *rt-hosting
          - *hosting-srv
          - *priv-home-srv
          - *proxy-home

    # generic secrets
  - path_regex: "nix/data/secrets/.+.yml"
    key_groups:
      - age: [ *lilly ]
  - path_regex: "dotfiles/.+\\.secret\\..+"
    key_groups:
      - age: [ *lilly ]
