apiVersion: v1
kind: List
items:

  # service
  - apiVersion: v1
    kind: Service
    metadata:
      name: taskchampion-sync-server
      labels: &labels
        app.kubernetes.io/name: taskchampion-sync-server
    spec:
      selector: *labels
      ports:
        - name: http
          port: 80
          targetPort: http

  # deployment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: taskchampion-sync-server
      labels: *labels
    spec:
      selector:
        matchLabels: *labels
      template:
        metadata:
          labels: *labels
        spec:
          containers:
            - name: taskchampion-sync-server
              image: ghcr.io/gothenburgbitfactory/taskchampion-sync-server-postgres
              envFrom:
                - secretRef:
                    name: taskchampion-sync-server-env
              ports:
                - name: http
                  containerPort: 8080
              readinessProbe:
                httpGet:
                  port: http
