apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-riddles
  labels: &labels
    app.kubernetes.io/name: website-riddles
    app.kubernetes.io/component: riddles-server
spec:
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: riddles
          image: git.lly.sh/lilly/homepage-riddles
          envFrom:
            - secretRef:
                name: website-riddles
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            tcpSocket:
              port: http
          resources:
            requests:
              cpu: "0.5"
              memory: "500M"
            limits:
              cpu: "2"
              memory: "1G"
