apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: cert-manager

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.19.1/cert-manager.yaml
  - issuers.yml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager
    path: controller-deployment.patch.yml
