apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: cert-manager

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.16.1/cert-manager.yaml
  - issuers.yml
