name: containers
on:
  push:
    paths: [ "containers/**", ".forgejo/workflows/containers.yml" ]
  workflow_dispatch: {}
  schedule:
    - cron: "@weekly"

jobs:
  generate-build-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - id: discover-containers
        name: Discover contained container definitions
        shell: "python3 {0}"
        run: |
          import json
          import os
          with open(os.environ["FORGEJO_OUTPUT"], "a") as f:
            container_names = os.listdir("containers/")
            print(f"Found container definitions {container_names}")
            print(f"container_names={json.dumps(container_names)}", file=f)
    outputs:
      container_names: ${{ steps.discover-containers.outputs.container_names }}

  build-container:
    runs-on: alpine-latest
    needs: [ generate-build-matrix ]
    strategy:
      matrix: 
        container_name: ${{ fromJSON(needs.generate-build-matrix.outputs.container_names) }}
    container:
      image: ghcr.io/osscontainertools/kaniko:alpine
    steps:
      - name: Install required system packages
        run: apk add --no-cache nodejs git

      - name: Checkout source code
        uses: actions/checkout@v7

      - name: Build Container Image
        env:
          KANIKO_NO_PUSH: ${{ forgejo.ref_name != 'main' }}
          KANIKO_GIT_HANSE_DE_USER: forgejo-actions
          KANIKO_GIT_HANSE_DE_PASSWORD: ${{ secrets.HANSE_PACKAGES_ACCESS }}
        run: /kaniko/executor
          --dockerfile="${{ forgejo.workspace }}/containers/${{ matrix.container_name }}/Containerfile" 
          --context="dir://${{ forgejo.workspace }}/containers/${{ matrix.container_name }}"
          --destination=git.hanse.de/${{ forgejo.repository }}-${{ matrix.container_name }}:latest
          --no-push-cache
          --credential-helpers=env
          --annotation=org.opencontainers.image.source=${{ forgejo.server_url }}/${{ forgejo.repository }}
