apiVersion: apps/v1
kind: CronJob
metadata:
  name: nextcloud-cron
  labels: &labels
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/component: cron
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels: *labels
    spec: # job spec
      backoffLimit: 0
      template: # pod template
        metadata:
          labels: *labels
        spec: # pod spec
          securityContext:
            fsGroup: 2000
          volumes:
            - name: installation
              persistentVolumeClaim:
                claimName: nextcloud
          containers:
            - name: cron
              image: docker.io/nextcloud
              imagePullPolicy: Always
              command: [ "su", "-c", "/var/www/occ", "cron" ]
              env:
                - name: PHP_UPLOAD_LIMIT
                  value: 2G
                - name: OVERWRITEPROTOCOL
                  value: https
              volumeMounts:
                - name: installation
                  mountPath: /var/www/html
              resources:
                requests:
                  cpu: "100m"
                limits:
                  memory: "200Mi"
