apiVersion: v1
kind: List
items:

  # service
  - apiVersion: v1
    kind: Service
    metadata:
      name: redis
      labels: &labels
        app.kubernetes.io/name: redis
        app.kubernetes.io/component: cache-server
    spec:
      selector: *labels
      ports:
        - name: redis
          port: 6379
          targetPort: redis

  # deployment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: redis
      labels: *labels
    spec:
      selector:
        matchLabels: *labels
      template:
        metadata:
          labels: *labels
        spec:
          containers:
            - name: redis
              image: docker.io/redis
              ports:
                - name: redis
                  containerPort: 6379
              readinessProbe:
                tcpSocket:
                  port: redis
              resources:
                requests:
                  cpu: "20m"
                limits:
                  memory: "300Mi"
