# ref: https://github.com/viaduct-ai/kustomize-sops
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
secretFrom:
  - metadata:
      name: argocd-secret
      annotations:
        kustomize.config.k8s.io/behavior: replace
    envs:
      - ./config/argocd.secret.env

  - metadata:
      name: age-keys
    files:
      - "keys.txt=./config/sops-key.secret.txt"

  - metadata:
      name: lillinfra-repo-creds
      labels:
        argocd.argoproj.io/secret-type: repository
    stringData:
      url: "git@git.lly.sh:lilly/lillinfra.git"
    files:
      - "sshPrivateKey=./config/id_argocd.secret.txt"
  
