# ref: https://github.com/viaduct-ai/kustomize-sops
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
secretFrom:
  - metadata:
      name: cache-signing-keys
    files:
      - "cache-key.secret.txt=config/cache-key.secret.txt"

  - metadata:
      name: sshd-keys
    files:
      - "ssh_host_ed25519_key=config/ssh_host_ed25519_key.secret.txt"
  
