# ref: https://github.com/viaduct-ai/kustomize-sops
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
secretFrom:
  - metadata:
      name: github-packages-creds
      annotations:
        kustomize.config.k8s.io/needs-hash: false
    type: kubernetes.io/dockerconfigjson
    files:
      - ".dockerconfigjson=dockerconfig-github.secret.json"

  - metadata:
      name: dockerhub-creds
      annotations:
        kustomize.config.k8s.io/needs-hash: false
    type: kubernetes.io/dockerconfigjson
    files:
      - ".dockerconfigjson=dockerconfig-dockerhub.secret.json"

  - metadata:
      name: own-forgejo-creds
      annotations:
        kustomize.config.k8s.io/needs-hash: false
    type: kubernetes.io/dockerconfigjson
    files:
      - ".dockerconfigjson=dockerconfig-own-forgejo.secret.json"
