apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          volumes:
            - name: cache
              emptyDir: {}
          restartPolicy: Never
          containers:
            - name: renovate
              image: docker.io/renovate/renovate
              envFrom:
                - secretRef:
                    name: renovatebot-config
                - configMapRef:
                    name: renovatebot-config
              volumeMounts:
                - name: cache
                  mountPath: /tmp/renovate/
              resources:
                requests:
                  cpu: "500m"
                limits:
                  memory: "1Gi"
