apiVersion: v1
kind: List
items:

  # service
  - apiVersion: v1
    kind: Service
    metadata:
      name: immich-ml
      labels: &labels
        app.kubernetes.io/name: immich-ml
        app.kubernetes.io/component: machine-learning-worker
    spec:
      selector: *labels
      ports:
        - name: http
          port: 3003
          targetPort: http


  # deployment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: immich-ml
      labels: *labels
    spec:
      selector:
        matchLabels: *labels
      template:
        metadata:
          labels: *labels
        spec:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 50
                  podAffinityTerm:
                    labelSelector:
                      matchLabels: *labels
                    topologyKey: kubernetes.io/hostname
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: immich-data
          containers:
            - name: immich
              image: ghcr.io/immich-app/immich-machine-learning
              env:
                - name: IMMICH_HOST
                  #value: "0.0.0.0"
                  value: "[::]"
              envFrom:
                - secretRef:
                    name: immich-env
              volumeMounts:
                - name: data
                  mountPath: /data
              ports:
                - name: http
                  containerPort: 3003
              readinessProbe:
                httpGet:
                  port: http
