apiVersion: v1
kind: List
items:

  # slow (hdd) storage class
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: nfs-slow
    provisioner: nfs.csi.k8s.io
    parameters:
      server: 10.0.10.14
      share: /srv/hdd/k8s
      subDir: "${pvc.metadata.namespace}--${pvc.metadata.name}--${pv.metadata.name}"
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true

  # fast (ssd) storage class
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: nfs-fast
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
    provisioner: nfs.csi.k8s.io
    parameters:
      server: 10.0.10.14
      share: /srv/ssd/k8s
      subDir: "${pvc.metadata.namespace}--${pvc.metadata.name}--${pv.metadata.name}"
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
