apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      volumes:
        - name: age-keys
          secret:
            secretName: age-keys
      containers:
        - name: argocd-repo-server
          env:
            - name: SOPS_AGE_KEY_FILE
              value: /app/config/age-keys/keys.txt
            - name: PATH
              value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/argocd/cmp-server/plugins"
          volumeMounts:
            - name: age-keys
              mountPath: /app/config/age-keys
      initContainers:
        - name: install-ksops
          image: quay.io/viaductoss/ksops
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Installing KSOPS..."
              mv ksops /plugins/
              echo "Done."
          volumeMounts:
            - mountPath: /plugins
              name: plugins
