apiVersion: v1
kind: List
items:

  # service
  - apiVersion: v1
    kind: Service
    metadata:
      name: harmonia
      labels: &labels
        app.kubernetes.io/name: harmonia
        app.kubernetes.io/component: webserver
    spec:
      selector: *labels
      ports:
        - port: 5000
          name: http
          targetPort: http

  # deployment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: harmonia
      labels: *labels
    spec:
      selector:
        matchLabels: *labels
      template:
        metadata:
          labels: *labels
        spec:

          volumes:
            - name: config
              configMap:
                name: harmonia-config
            - name: signing-keys
              secret:
                secretName: cache-signing-keys
            - name: guest-store
              persistentVolumeClaim:
                claimName: harmonia-store

          containers:
            - name: harmonia
              image: git.lly.sh/lilly/harmonia
              env:
                - name: CONFIG_FILE
                  value: "/etc/harmonia/config.toml"
                - name: SIGN_KEY_PATHS
                  value: "/run/harmonia/cache-signing-key.txt"
              volumeMounts:
                - name: config
                  mountPath: /etc/harmonia/config.toml
                  subPath: config.toml
                - name: signing-keys
                  mountPath: /run/harmonia/cache-signing-key.txt
                  subPath: cache-key.secret.txt
                - name: guest-store
                  mountPath: /srv/guest-store
              ports:
                - name: http
                  containerPort: 5000
              readinessProbe:
                httpGet:
                  port: http
              resources:
                requests:
                  cpu: "0.1"
                limits:
                  memory: "200M"
