apiVersion: v1
kind: List
items:

  # service
  - apiVersion: v1
    kind: Service
    metadata:
      name: store-ssh
      labels: &labels
        app.kubernetes.io/name: openssh
        app.kubernetes.io/component: store-ssh-gateway
    spec:
      type: NodePort
      selector: *labels
      ports:
        - name: ssh
          port: 22
          targetPort: 22
          nodePort: 30122

  # deployment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: store-ssh
      labels: *labels
    spec:
      selector:
        matchLabels: *labels
      template:
        metadata:
          labels: *labels
        spec:

          volumes:
            - name: config
              configMap:
                name: sshd-config
            - name: sshd-keys
              secret:
                secretName: sshd-keys
                defaultMode: 0400
            - name: guest-store
              persistentVolumeClaim:
                claimName: harmonia-store

          containers:
            - name: sshd
              image: git.lly.sh/lilly/openssh
              volumeMounts:
                - name: config
                  mountPath: /etc/ssh/sshd_config
                  subPath: sshd_config
                - name: sshd-keys
                  mountPath: /etc/ssh/ssh_host_ed25519_key
                  subPath: ssh_host_ed25519_key
                - name: guest-store
                  mountPath: /srv/guest-store
              ports:
                - name: ssh
                  containerPort: 22
              readinessProbe:
                tcpSocket:
                  port: ssh
              resources:
                requests:
                  cpu: "0.2"
                limits:
                  memory: "500M"
                
          

