apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harmonia-store
  labels:
    app.kubernetes.io/name: harmonia
    app.kubernetes.io/component: nix-store
spec:
  storageClassName: nfs-slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "20G"
