# ref: https://github.com/viaduct-ai/kustomize-sops
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
secretFrom:
  - metadata:
      name: website-riddles
    envs:
      - configs/riddles.secret.env

  - metadata:
      name: website-env
    envs:
      - configs/website.secret.env
