apiVersion: v1
kind: List
items:

  # service
  - apiVersion: v1
    kind: Service
    metadata:
      name: wiki-server
      labels: &labels
        app.kubernetes.io/name: wiki
        app.kubernetes.io/component: server
    spec:
      selector: *labels
      ports:
        - name: http
          port: 80
          targetPort: http

  # deployment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: wiki-server
      labels: *labels
    spec:
      replicas: 0
      selector:
        matchLabels: *labels
      template:
        metadata:
          labels: *labels
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
          volumes:
            - name: storage
              persistentVolumeClaim:
                claimName: dokuwiki-storage
          containers:
            - name: dokuwiki
              image: ghcr.io/dokuwiki/dokuwiki
              envFrom:
                - configMapRef:
                    name: wiki-server-env
              volumeMounts:
                - name: storage
                  mountPath: /storage
              ports:
                - name: http
                  containerPort: 8080
              readinessProbe:
                httpGet:
                  port: http
                  path: /health.php
              resources:
                requests:
                  cpu: "100m"
                  memory: "320Mi"
                limits:
                  memory: "320Mi"

  # PVC
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: dokuwiki-storage
      labels: *labels
    spec:
      accessModes: [ ReadWriteMany ]
      storageClassName: nfs-fast
      resources:
        requests:
          storage: 2G
