apiVersion: v1
kind: List
items:

  # service
  - apiVersion: v1
    kind: Service
    metadata:
      name: ntfy
      labels: &labels
        app.kubernetes.io/name: ntfy
        app.kubernetes.io/component: server
    spec:
      selector: *labels
      ports:
        - name: http
          port: 80
          targetPort: http

  # deployment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nfy
      labels: *labels
    spec:
      selector:
        matchLabels: *labels
      template:
        metadata:
          labels: *labels
        spec:
          priorityClassName: custom-high
          volumes:
            - name: config
              configMap:
                name: ntfy-config
            - name: storage
              persistentVolumeClaim:
                claimName: ntfy
          containers:
            - name: ntfy
              image: docker.io/binwiederhier/ntfy
              args: [ "serve" ]
              volumeMounts:
                - name: config
                  mountPath: /etc/ntfy
                - name: storage
                  mountPath: /var/lib/ntfy
              ports:
                - name: http
                  containerPort: 80
              readinessProbe:
                httpGet:
                  port: http
                  path: /v1/health
              resources:
                requests:
                  cpu: "10m"
                limits:
                  memory: "50Mi"

  # storage
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ntfy
      labels: *labels
    spec:
      accessModes: [ ReadWriteOnce ]
      storageClassName: nfs-fast
      resources:
        requests:
          storage: "1G"

