apiVersion: v1
kind: List
items:

  # service
  - apiVersion: v1
    kind: Service
    metadata:
      name: tracker-server
      labels: &labels
        app.kubernetes.io/name: tracker
        app.kubernetes.io/component: server
    spec:
      selector: *labels
      ports:
        - name: http
          port: 80
          targetPort: http

  # deployment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: tracker-server
      labels: *labels
    spec:
      selector:
        matchLabels: *labels
      template:
        metadata:
          labels: *labels
        spec:
          containers:
            - name: tracker
              image: git.lly.sh/lilly/tracker
              envFrom:
                - secretRef:
                    name: tracker-server-env
              ports:
                - name: http
                  containerPort: 8000
              readinessProbe:
                httpGet:
                  port: http
                  path: /admin/login/
                  httpHeaders:
                    - name: Host
                      value: tracker.lly.sh
              resources:
                requests:
                  cpu: "100m"
                  memory: "250Mi"
                limits:
                  memory: "1Gi"
