# ref: https://github.com/viaduct-ai/kustomize-sops
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
secretFrom:
  - metadata:
      name: mailserver
    files:
      - opendkim_key.pem=configs/dkim_key.secret.pem
      - dovecot-oauth2.conf.ext=configs/oauth2.secret.conf
      - dovecot-ldap.conf.ext=configs/ldap.secret.conf
      - fetchmailrc=configs/fetchmailrc.secret.txt
 
