apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels: &labels
    app.kubernetes.io/name: website
    app.kubernetes.io/component: website-server
spec:
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      securityContext:
        fsGroup: 10000
      volumes:
        - name: state
          persistentVolumeClaim:
            claimName: homepage-state
      containers:
        - name: homepage
          image: git.lly.sh/lilly/homepage
          args: [ "--ipv6", "[::]:8000" ]
          envFrom:
            - secretRef:
                name: website-env
          volumeMounts:
            - name: state
              mountPath: /var/lib/homepage/
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            httpGet:
              port: http
              httpHeaders:
                - name: Host
                  value: li.lly.sh
          resources:
            requests:
              cpu: "100m"
            limits:
              memory: "200Mi"
