apiVersion: v1
kind: Service
metadata:
  name: website
  labels: &labels
    app.kubernetes.io/name: website
    app.kubernetes.io/component: website-server
spec:
  selector: *labels
  ports:
    - name: http
      port: 80
      targetPort: http
