apiVersion: v1
kind: List
items:

  # service
  - apiVersion: v1
    kind: Service
    metadata:
      name: mediamtx
      labels: &labels
        app.kubernetes.io/name: mediamtx
        app.kubernetes.io/component: streaming-server
    spec:
      selector: *labels
      ports:
        - name: http
          port: 8888
          targetPort: http
        - name: rtmp
          port: 1935
          targetPort: rtmp
        - name: rtsp
          port: 8554
          targetPort: rtsp

  # deployment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: mediamtx
      labels: *labels
    spec:
      selector:
        matchLabels: *labels
      template:
        metadata:
          labels: *labels
        spec:
          volumes:
            - name: config
              configMap:
                name: mediamtx
          containers:
            - name: mediamtx
              image: docker.io/bluenviron/mediamtx:latest-ffmpeg
              imagePullPolicy: Always
              volumeMounts:
                - name: config
                  mountPath: /mediamtx.yml
                  subPath: mediamtx.yml
              ports:
                - name: http
                  containerPort: 8888
                - name: rtmp
                  containerPort: 1935
                - name: rtsp
                  containerPort: 8554
                - name: webrtc-udp
                  containerPort: 30189
                  protocol: UDP
                - name: webrtc-tcp
                  containerPort: 30189
                  protocol: TCP
              resources:
                request:
                  memory: "10Mi"
                limits:
                  memory: "100Mi"
