apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-data
  labels:
    app.kubernetes.io/name: actual-budget
    app.kubernetes.io/component: webserver
spec:
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: "2G"
