# ref: https://github.com/viaduct-ai/kustomize-sops
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
secretFrom:
  - metadata:
      name: tsig-gruenkohl.org-lilly
      namespace: "cert-manager"
      annotations:
        kustomize.config.k8s.io/needs-hash: "false"
    files:
      - "key=./tsig-gruenkohl.org-lilly.secret.txt" 

