apiVersion: v1
kind: List
items:

  # service
  - apiVersion: v1
    kind: Service
    metadata:
      name: woodpecker-agent
      labels: &labels
        app.kubernetes.io/name: woodpecker-agent
        app.kubernetes.io/component: ci-runner
    spec:
      selector: *labels
      clusterIP: None

  # limit-range to constrain ci job resource consumption
  - apiVersion: v1
    kind: LimitRange
    metadata:
      name: ci-job-resources
      labels: *labels
    spec:
      limits:
        - type: Container
          defaultRequest:
            cpu: "2"
          default: # default limit
            memory: "1Gi"
          max: # maximum allowed limit
            memory: "8Gi"

  # pod statefulset
  - apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: woodpecker-agent
      labels: *labels
    spec:
      serviceName: woodpecker-agent
      selector:
        matchLabels: *labels

      volumeClaimTemplates:
        - metadata:
            name: agent-config
          spec:
            storageClassName: nfs-fast
            accessModes: [ "ReadWriteMany" ]
            resources:
              requests:
                storage: "1G"

      template:
        metadata:
          labels: *labels
        spec:
          serviceAccountName: woodpecker-agent
          containers:
            - name: agent
              image: git.lly.sh/lilly/woodpecker-agent
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: woodpecker-agent
              env:
                - name: WOODPECKER_AGENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: woodpecker-server
                      key: WOODPECKER_AGENT_SECRET
              volumeMounts:
                - name: agent-config
                  mountPath: /etc/woodpecker
              ports:
                - name: http
                  containerPort: 3000
              resources:
                requests:
                  cpu: "10m"
                limits:
                  memory: "50Mi"
