apiVersion: v1
kind: List
items:

  # https://woodpecker-ci.org/docs/next/administration/backends/kubernetes#volumes
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: woodpecker-cache
    spec:
      storageClassName: nfs-fast
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: "10G"

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: woodpecker-nix
    spec:
      storageClassName: nfs-slow
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: "50G"
