apiVersion: v1
kind: List
items:

  # service
  - apiVersion: v1
    kind: Service
    metadata:
      name: redis-cache
      labels: &labels
        app.kubernetes.io/name: redis
        app.kubernetes.io/component: cache-server
    spec:
      selector: *labels
      ports:
        - name: redis
          port: 6379
          targetPort: redis

  # storage
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: redis-cache
      labels: *labels
    spec:
      storageClassName: nfs-fast
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 1G

  # deployment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: redis-cache
      labels: *labels
    spec:
      strategy:
        type: Recreate
      selector:
        matchLabels: *labels
      template:
        metadata:
          labels: *labels
        spec:
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: redis-cache
          containers:
            - name: redis
              image: docker.io/redis
              imagePullPolicy: Always
              volumeMounts:
                - name: data
                  mountPath: /data
              ports:
                - name: redis
                  containerPort: 6379
              readinessProbe:
                tcpSocket:
                  port: redis
              resources:
                requests:
                  cpu: "20m"
                limits:
                  memory: "300Mi"
