apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: woodpecker

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: woodpecker

resources:
  - manifests/namespace.yml
  - manifests/rbac.yml
  - manifests/server.yml
  - manifests/agent.yml
  - manifests/job-helpers.yml
  - manifests/ingress.yml

images:
  - name: docker.io/woodpeckerci/woodpecker-server
    newTag: "v3.3.0"
  - name: docker.io/woodpeckerci/woodpecker-agent
    newTag: "v3.3.0"

replicas:
  - name: woodpecker-agent
    count: 3

configMapGenerator:
  - name: woodpecker-server
    envs:
      - config/server.env
  - name: woodpecker-agent
    envs:
      - config/agent.env

generators:
  - ./secret-generator.yml
