---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: imagepullsecret-patcher



---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagepullsecret-patcher
  labels:
    app.kubernetes.io/name: imagepullsecret-patcher
rules:
  - apiGroups: [ "" ]
    resources:
      - secrets
    verbs:
      - list
      - get
      - create
      - patch
      - delete
  - apiGroups: [ "" ]
    resources:
      - serviceaccounts
    verbs:
      - list
      - get
      - patch
  - apiGroups: [ "" ]
    resources:
      - namespaces
    verbs:
      - list
      - get



---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: imagepullsecret-patcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: imagepullsecret-patcher
subjects:
  - kind: ServiceAccount
    name: imagepullsecret-patcher