apiVersion: v1
kind: List
items:
  # service
  - apiVersion: v1
    kind: Service
    metadata:
      name: dovecot
      labels: &labels
        app.kubernetes.io/name: dovecot
        app.kubernetes.io/component: MDA
        app.kubernetes.io/part-of: mailserver
    spec:
      selector: *labels
      ports:
        - name: doveadm
          port: 2425
          targetPort: doveadm
        - name: stats
          port: 9090
        - name: lmtps
          targetPort: lmtps
          port: 31024
        - name: imap
          port: 31143
          targetPort: imap
        - name: imaps
          port: 31993
          targetPort: imaps
        - name: managesieve
          port: 34190
          targetPort: managesieve
        - name: sasl
          port: 3000
          targetPort: sasl

  # deployment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: dovecot
      labels: *labels
    spec:
      strategy:
        type: Recreate
      selector:
        matchLabels: *labels
      template:
        metadata:
          labels: *labels
        spec:
          enableServiceLinks: false
          automountServiceAccountToken: false
          priorityClassName: custom-high
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
          volumes:
            - name: mail-data
              persistentVolumeClaim:
                claimName: dovecot-mail
            - name: plaintext-configs
              configMap:
                name: dovecot-configs
            - name: secret-configs
              secret:
                secretName: dovecot-configs
            - name: tls-material
              secret:
                secretName: tls-mx2.z9.aut-num.de
          containers:
            - name: dovecot
              image: docker.io/dovecot/dovecot
              volumeMounts:
                - mountPath: /srv/vmail
                  name: mail-data
                - mountPath: /etc/dovecot/conf.d/local.conf
                  name: plaintext-configs
                  subPath: local.conf
                - mountPath: /etc/dovecot/conf.d/fts.conf
                  name: plaintext-configs
                  subPath: fts.conf
                - mountPath: /etc/dovecot/conf.d/sieve.conf
                  name: plaintext-configs
                  subPath: sieve.conf
                - mountPath: /etc/dovecot/conf.d/sasl.conf
                  name: plaintext-configs
                  subPath: sasl.conf
                - mountPath: /etc/dovecot/conf.d/auth.conf
                  name: secret-configs
                  subPath: auth.conf
                - mountPath: /etc/dovecot/dovecot-extra.passwd
                  name: secret-configs
                  subPath: dovecot-extra.passwd
                - mountPath: /etc/dovecot/ssl/
                  name: tls-material
              ports:
                - name: doveadm
                  containerPort: 2425
                - name: stats
                  containerPort: 9090
                - name: lmtps
                  containerPort: 31024
                - name: imap
                  containerPort: 31143
                - name: imaps
                  containerPort: 31993
                - name: managesieve
                  containerPort: 34190
                - name: sasl
                  containerPort: 3000
              readinessProbe:
                exec:
                  command: [ "doveadm", "service", "status" ]

  # actual mail storage
  # very important to back up!
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: dovecot-mail
      labels: *labels
    spec:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 10Gi
