apiVersion: v1
kind: List
items:

  # service
  - apiVersion: v1
    kind: Service
    metadata:
      name: mail-proxy
      labels: &labels
        app.kubernetes.io/name: mail-proxy
        app.kubernetes.io/component: ingress
        app.kubernetes.io/part-of: mailserver
    spec:
      selector: *labels
      type: LoadBalancer
      ipFamilies: [ IPv6, IPv4 ]
      ipFamilyPolicy: RequireDualStack
      ports:
        - name: smtp
          port: 25
          targetPort: smtp
        - name: submission
          port: 587
          targetPort: submission
        - name: imaps
          port: 993
          targetPort: imaps
        - name: managesieve
          port: 4190
          targetPort: managesieve

  # deployment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: mail-proxy
      labels: *labels
    spec:
      selector:
        matchLabels: *labels
      template:
        metadata:
          labels: *labels
        spec:
          enableServiceLinks: false
          automountServiceAccountToken: false
          priorityClassName: custom-high
          volumes:
            - name: config
              configMap:
                name: haproxy-config
          containers:
            - name: haproxy
              image: docker.io/haproxy
              volumeMounts:
                - mountPath: /usr/local/etc/haproxy
                  name: config
              ports:
                - name: smtp
                  containerPort: 25
                - name: submission
                  containerPort: 587
                - name: imaps
                  containerPort: 993
                - name: managesieve
                  containerPort: 4190

