---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailserver-mails
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20G



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailserver-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
