apiVersion: v1
kind: List
items:

  # service
  - apiVersion: v1
    kind: Service
    metadata:
      name: unbound
      labels: &labels
        app.kubernetes.io/name: unbound
        app.kubernetes.io/component: dns-resolver
        app.kubernetes.io/part-of: mailserver
    spec:
      selector: *labels
      ports:
        - name: dns-tcp
          port: 53
          protocol: TCP
        - name: dns-udp
          port: 53
          protocol: UDP

  # deployment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: unbound
      labels: *labels
    spec:
      selector:
        matchLabels: *labels
      template:
        metadata:
          labels: *labels
        spec:
          volumes:
            - name: config
              configMap:
                name: unbound-config
          containers:
            - name: unbound
              image: docker.io/alpinelinux/unbound
              volumeMounts:
                - name: config
                  mountPath: /etc/unbound/unbound.conf
                  subPath: unbound.conf
              ports:
                - name: dns-tcp
                  containerPort: 53
                  protocol: TCP
                - name: dns-udp
                  containerPort: 53
                  protocol: UDP
              readinessProbe:
                tcpSocket:
                  port: dns-tcp
          

