# overwrite list of enabled protocols to disable submission
protocols = imap lmtp sieve

# overwrite hostname to the static name that is also validated with TLS
hostname = mx2.z9.aut-num.de

service doveadm {
  inet_listener doveadm {
    port = 2425
  }
}

service lmtp {
  inet_listener lmtps {
    ssl = no
  }
}
