# overwrite list of enabled protocols to disable submission
protocols = imap lmtp sieve

# overwrite hostname to the static name that is also validated with TLS
hostname = mx2.z9.aut-num.de

haproxy_trusted_networks = 2a07:c481:2:100::/56 10.42.0.0/16

service doveadm {
  inet_listener doveadm {
    port = 2425
  }
}

service lmtp {
  inet_listener lmtps {
    ssl = no
  }
}

service imap-login {
  inet_listener imaps {
    haproxy = yes
  }
}

service managesieve-login {
  inet_listener sieve {
    haproxy = yes
  }
}
