sieve_trace_debug = yes
sieve_trace_dir = /tmp/

sieve_plugins {
	sieve_extprograms = yes
	sieve_imapsieve = yes
}

sieve_extensions {
	"vnd.dovecot.environment" = yes
	"vnd.dovecot.pipe" = yes
}

sieve_pipe_bin_dir = /usr/local/libexec/sieve

sieve_script before {
  path = /etc/dovecot/sieve/file-spam.sieve
  type = before
}

imapsieve_from Junk {
  sieve_script report-ham {
    type = before
	cause = copy
    path = /etc/dovecot/sieve/report-ham.sieve
  }
}

sieve_script report-spam {
  type = before
  cause = copy
  path = /etc/dovecot/sieve/report-spam.sieve
}
