sieve_plugins = sieve_extprograms
#sieve_global_extensions = +vnd.dovecot.environment
sieve_extensions {
	"vnd.dovecot.environment" = yes
	"vnd.dovecot.pipe" = yes
}

# sieve_script personal {
  # path = ~/.dovecot.sieve
# }

# sieve_script before {
# 	path = /etc/dovecot/sieve-scripts-before/
# 	# TODO: Actually place a script here that moves flagged mail into Junk folder
# }
