---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailserver-mails
spec:
  storageClassName: nfs-fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailserver-data
spec:
  storageClassName: nfs-fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
