matrix:
  CONTAINER:
    - pre-commit

steps:
  - name: build ${CONTAINER} container image
    when:
      - event: push
        path: [ ".woodpecker/build-containers.yml", "containers/${CONTAINER}.Containerfile" ]
      - event: cron
        cron: build-containers
      - event: manual
    image: quay.io/containers/podman
    privileged: true
    volumes:
      - woodpecker-cache:/woodpecker/src/cache
    environment:
      XDG_CACHE_HOME: /woodpecker/src/cache
    commands:
      - podman build -t git.lly.sh/lilly/lillinfra-${CONTAINER} -f containers/${CONTAINER}.Containerfile containers
      - podman save -o ${CONTAINER}.tar git.lly.sh/lilly/lillinfra-${CONTAINER}

  - name: publish ${CONTAINER} container image
    when:
      - event: manual
        branch: main
      - event: push
        branch: main
        path: [ ".woodpecker/build-containers.yml", "containers/${CONTAINER}.Containerfile" ]
      - event: cron
        cron: periodic-rebuild
    image: quay.io/containers/skopeo
    environment:
      FORGEJO_PACKAGES_ACCESS:
        from_secret: FORGEJO_PACKAGES_ACCESS
    commands:
      - skopeo copy --dest-username lilly --dest-password $FORGEJO_PACKAGES_ACCESS docker-archive:${CONTAINER}.tar docker://git.lly.sh/lilly/lillinfra-${CONTAINER}
