when:
  - event: push
    branch: main

matrix:
  SYSTEM_CONFIG:
    - lillysWorkstation
    - lillysLaptop

# don't clone the repo because nix can use git references
skip_clone: true

steps:
  - name: build-system
    image: docker.io/nixos/nix
    backend_options:
      kubernetes:
        resources:
          requests:
            cpu: "1"
            memory: "6Gi"
          limits:
            memory: "10Gi"
    environment:
      CACHE_URL: "https://babe-do-you-need-anything-from-the-nix.store/lillinfra"
      CACHE_TOKEN:
        from_secret: "babe-store-ci-token"
    commands:
      - nix
          --extra-experimental-features "nix-command flakes"
          --accept-flake-config
          build "git+${CI_REPO_CLONE_URL}#nixosConfigurations.\"${SYSTEM_CONFIG}\".config.system.build.toplevel"
      - nix 
          --extra-experimental-features "nix-command flakes" 
          run nixpkgs#attic-client login babe-store "${CACHE_URL}" "${CACHE_TOKEN}"
      - nix 
          --extra-experimental-features "nix-command flakes"
          run nixpkgs#attic push lillinfra ./result
