when:
  # only trigger on the update-flake pull request because only there, creating comments makes sense
  - event: pull_request
    evaluate: >-
      CI_COMMIT_SOURCE_BRANCH == "update-flake-inputs"

matrix:
  SYSTEM_CONFIG:
    - lillysWorkstation
    - lillysLaptop

steps:
  - name: render-diff
    image: docker.io/nixos/nix
    backend_options:
      kubernetes:
        resources:
          requests:
            cpu: "4"
          limits:
            memory: "8Gi"
    commands:
      - nix --extra-experimental-features "nix-command flakes" --accept-flake-config run ".#show-nixos-diff" -- --flake "$(pwd)" "${CI_COMMIT_BRANCH}" "${CI_COMMIT_SOURCE_BRANCH}" "${SYSTEM_CONFIG}" > diff.txt
      - cat diff.txt
