when:
  - evaluate: |
      // Trigger when the update-flake-inputs PR is created
      (CI_PIPELINE_EVENT == "pull_request" and CI_COMMIT_SOURCE_BRANCH == "update-flake-inputs")ß
      // Also trigger when relevant nix files are changed
      or any(CI_PIPELINE_FILES, # matches "^(flake.lock)|(flake.nix)|(nix/systems/.+)$")

matrix:
  SYSTEM_CONFIG:
    - lillysWorkstation
    - lillysLaptop

steps:
  - name: render-diff
    image: docker.io/nixos/nix
    backend_options:
      kubernetes:
        resources:
          requests:
            cpu: "4"
          limits:
            memory: "8Gi"
    commands:
      - nix --extra-experimental-features "nix-command flakes" --accept-flake-config run ".#show-nixos-diff" -- --flake "$(pwd)" "${CI_COMMIT_BRANCH}" "${CI_COMMIT_SOURCE_BRANCH}" "${SYSTEM_CONFIG}" > diff.txt
      - cat diff.txt
