when:
  - event: cron
    cron: update-flake-inputs

steps:
  - name: update-flake-inputs
    image: docker.io/nixos/nix
    backend_options:
      kubernetes:
        securityContext:
          fsGroupChangePolicy: "OnRootMismatch"
        resources:
          requests:
            cpu: "500m"
          limits:
            memory: "2Gi"
    commands:
      - nix
          --extra-experimental-features "nix-command flakes"
          --accept-flake-config
          run ".#ci-update-flakes"
