server:
  verbosity: 1
  logfile: /dev/stderr

  interface: 0.0.0.0
  interface: ::0

  module-config: "respip validator iterator"

  # more cache memory
  rrset-cache-size: 60m
  msg-cache-size: 30m

  # prefetch to keep the cache up to date
  prefetch: yes

  # fetch the DNSKEYs earlier in the validation process, when a DS record is encountered
  prefetch-key: yes

  # Faster UDP with multithreading (only on Linux).
  so-reuseport: yes

  # disable special large send buffer handling and just use kernel defaults
  so-sndbuf: 0

  # send minimal amount of information to upstream servers to enhance privacy
  qname-minimisation: yes

  # only allow querying from vpn IP range
  access-control: 2a07:c481:2:4::1/64 allow
  access-control: 10.233.228.1/24 allow

rpz:
  # https://github.com/hagezi/dns-blocklists
  name: dns-blocklists-pro
  url: "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/rpz/pro.txt"

