apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
  labels: &labels
    app.kubernetes.io/name: forgejo
    app.kubernetes.io/component: forgejo-server
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: forgejo-data

      containers:
        - name: forgejo
          image: codeberg.org/forgejo/forgejo
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: forgejo
            - secretRef:
                name: forgejo
          volumeMounts:
            - mountPath: /data
              name: data
          ports:
            - containerPort: 22
              name: ssh
            - containerPort: 3000
              name: http
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: http
          resources:
            requests:
              cpu: "500m"
              memory: "300M"
            limits:
              memory: "1G"
