# https://docs.rspamd.com/modules/dkim_signing

# our usernames are plain and we don't use per-domain config
# this allows plain username without @domain part
allow_username_mismatch = true;

# use static key
path = "/etc/rspamd/dkimkey.pem";
selector = "mx2";

