{
	"data": "ENC[AES256_GCM,data:5Z+jS11SXVVtMx/6XwXdlAh5VW4rBBIu3h+q9SNIQOVWQNkQs/LyvZtaHaR2gyGhhuW2Cwnzse9uzqsWK5aMN8pLIdHOwWjaeZNp9kJ4oF9hgpYUp9abnwl/DMfR7u6elk7GChj6wQ==,iv:+Mk1GZ4WDqi3ljyx+b6v84QkaCInS0ACiYtZiVO0VSk=,tag:tIBONh4CuNIvKx+aFRtvfw==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMT2dqbmZEZXJMZFJSekhn\nV0NSL0pjNmJwbzlGeTdLR2JiMkpwb2FUa0E0CjJMTzhxNWp5U2FzN09SNDhlbmth\nbncyaHNBTkdCK0N1TVZONDByUW0vS1EKLS0tIHZrN0Z5WHltUWNGckRKSlpPb3hW\nMzUyOWwyQ3ZtVCtWdUZ4SGRwNFdCSHcKUeKaCz2+k+yaDNvVNsgyzDEZkdcUuv+5\nGkYQUrSeyikiPH6olyeREdWpLgN1217uHBXX10MVWi8lCA39FREDbQ==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age19h7xtfmt3py3ydgl8d8fgh8uakxqxjr74flrxev3pgmvvx94kvtq5d932d"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMME4xSXk0Wk5GZmdXYTky\nM0FDNDI3V3Awb1BvUHcvOTk3L2VFQXJpbm5RCllydWlvVy9hemRvRk1nclRKb0Y2\nb3pzdWNTdW4xRE1ycHd4SUVGenEwRW8KLS0tIDBING1iOFcxSFJUeDVxNmNpWW9i\nYU4zNUxhazhucVhFZUhRbisxc1hXMlUKKiybjWperg0At+LGWdd1ZCpy3Fd6pSyh\nBKk8HBr1ZcDPDr4zmGpA7wApaf6uupslC8EsUCyN1cDWKkQEwNou5A==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1j2a8asttv66kkqk4008an46f4apjru9lgm0hxmvuuamlm5ts5f9qmzlx9y"
			}
		],
		"lastmodified": "2026-08-02T15:42:49Z",
		"mac": "ENC[AES256_GCM,data:1JTJUdnGE/ti5TOu5IlkLYkt66tk+fRqc0B7SNoAeMAZgh9VQ4I5WmQzWg4o4vdjAWytlFZCcOVMf/BSW7rNPxHakXp+71bqo8KQgjuKiVty4SzLjRQG7HC3kdaIeorV+NSJy8/dE2989njrSWvyz13S7cl8i9uu3USZ3PHfIA8=,iv:Kkn0srVRmSd0kgWQWr8hq69X5b+OE1Mxtuj5PLPGJGc=,tag:K6t58tjc7XPlLlmiZMI5WQ==,type:str]",
		"version": "3.13.3"
	}
}
