apiVersion: v1
kind: List
items:

  # service
  - apiVersion: v1
    kind: Service
    metadata:
      name: conduwuit
      labels: &labels
        app.kubernetes.io/name: conduwuit
        app.kubernetes.io/component: homeserver
    spec:
      selector: *labels
      ports:
        - name: http
          port: 80
          targetPort: http

  # deployment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: conduwuit
      labels: *labels
    spec:
      replicas: 1
      strategy:
        type: Recreate
      selector:
        matchLabels: *labels
      template:
        metadata:
          labels: *labels
        spec:
          enableServiceLinks: false
          volumes:
            - name: config
              configMap:
                name: conduwuit-config
            - name: data
              persistentVolumeClaim:
                claimName: conduwuit-data
          containers:
            - name: conduwuit
              image: ghcr.io/girlbossceo/conduwuit
              env:
                - name: CONDUWUIT_CONFIG
                  value: /etc/conduwuit/conduwuit.toml
              envFrom:
                - secretRef:
                    name: conduwuit-env
              volumeMounts:
                - name: config
                  mountPath: /etc/conduwuit
                - name: data
                  mountPath: /var/lib/conduwuit
              ports:
                - name: http
                  containerPort: 6167
              readinessProbe:
                httpGet:
                  port: http
                  path: /_conduwuit/server_version
              resources:
                requests:
                  cpu: "200m"
                limits:
                  memory: "500Mi"

  # storage
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: conduwuit-data
      labels: *labels
    spec:
      accessModes: [ ReadWriteMany ]
      storageClassName: nfs-slow
      resources:
        requests:
          storage: "10Gi"
        
