apiVersion: v1
kind: List
items:

  # service
  - apiVersion: v1
    kind: Service
    metadata:
      name: element-web
      labels: &labels
        app.kubernetes.io/name: element-web
        app.kubernetes.io/component: webclient
    spec:
      selector: *labels
      ports:
        - name: http
          port: 80
          targetPort: http

  # deployment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: element-web
      labels: *labels
    spec:
      selector:
        matchLabels: *labels
      template:
        metadata:
          labels: *labels
        spec:
          enableServiceLinks: false
          volumes:
            - name: config
              configMap:
                name: element-web
          containers:
            - name: element
              image: docker.io/vectorim/element-web
              ports:
                - name: http
                  containerPort: 80
              volumeMounts:
                - name: config
                  mountPath: /app/config.json
                  subPath: config.json
              readinessProbe:
                httpGet:
                  port: http
              resources:
                requests:
                  cpu: "10m"
                limits:
                  memory: "100Mi"

