apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: http-whoami

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: http-whoami

resources:
  - namespace.yml
  - deployment.yml
  - service.yml
  - ingress.yml
