[bar.default]
center = [ "active_window", "privacy" ]
end = [ "tray", "media", "notifications", "volume", "bluetooth", "network", "battery", "control-center" ]
start = [ "launcher", "workspaces", "clock" ]
thickness = 30
widget_spacing = 8

[calendar]
enabled = true

    [calendar.account.ccchh_public]
    name = "CCCHH Public"
    server_url = "webcal://cloud.hamburg.ccc.de/remote.php/dav/public-calendars/QJAdExziSnNJEz5g/?export"
    type = "ics"

[control_center.calendar]
show_week_numbers = true

[[control_center.shortcuts]]
type = "keyboard_layout"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "dark_mode"

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[hooks]
colors_changed = ""
theme_mode_changed = "systemctl --user reload app-com.mitchellh.ghostty.service"

[location]
address = "Hamburg, Germany"

[lockscreen]
blur_intensity = 0.0
tint_intensity = 0.0
wallpaper = "/home/lilly/Sync/Wallpapers/ccc-camp.jpg"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@WL-1",
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@WL-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 358.0
    cy = 663.0
    output = "WL-1"
    placement_height = 845.0
    placement_width = 716.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@WL-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 1028.5
    cy = 1221.82080078125
    output = "eDP-1"
    placement_height = 1285.0
    placement_width = 2057.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.0
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = false
        show_unlock_hint = false
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 112.0
    box_width = 240.0
    cx = 1028.5
    cy = 85.666664123535156
    output = "eDP-1"
    placement_height = 1285.0
    placement_width = 2057.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        center_text = true
        clock_style = "digital"
        color = "primary"
        shadow = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 176.0
    box_width = 416.0
    cx = 236.76927185058594
    cy = 1177.9166259765625
    output = "eDP-1"
    placement_height = 1285.0
    placement_width = 2057.0
    rotation = 0.0
    type = "media_player"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        hide_when_no_media = true
        layout = "horizontal"
        shadow = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 0.0
    box_width = 0.0
    cx = 2010.9317626953125
    cy = 1259.300048828125
    output = "eDP-1"
    placement_height = 1285.0
    placement_width = 2057.0
    rotation = 0.0
    type = "label"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background = false
        color = "on_tertiary"
        description = "li@lly.sh"
        shadow = false
        title = ""

[notification]
history_retention_hours = 3
max_visible = 3

[osd]
position = "top_right"

    [osd.kinds]
    keyboard_backlight = false
    lock_keys = false
    media = false

[shell]
avatar_path = "/home/lilly/Sync/ProfilePictures/poly_fox.jpg"
clipboard_enabled = false
clipboard_keep_from_closed_apps = false
settings_show_advanced = true

    [shell.launcher]
    fetch_exchange_rates = false

    [shell.panel]
    open_near_click_control_center = true
    open_near_click_session = true
    session_position = "center"

    [shell.session]
    show_shortcuts = false

[theme]
builtin = "Rosé Pine"
community_palette = "Oxocarbon"
mode = "auto"
pure_black_dark = true
source = "builtin"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "ghostty", "helix", "qt" ]

[wallpaper]
directory = "/home/lilly/Sync/Wallpapers"
directory_dark = "/home/lilly/Sync/Wallpapers/darkmode"
directory_light = "/home/lilly/Sync/Wallpapers/lightmode"

    [wallpaper.automation]
    enabled = true

    [wallpaper.default]
    path = "/home/lilly/Sync/Wallpapers/lightmode/daniel-clarke-yb-30sec-sh020-bg-paint-v021.jpg"

    [wallpaper.last]
    path = "/home/lilly/Sync/Wallpapers/lightmode/daniel-clarke-yb-30sec-sh020-bg-paint-v021.jpg"

    [wallpaper.monitors.WL-1]
    path = "/home/lilly/Sync/Wallpapers/darkmode/nasa-53884.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/lilly/Sync/Wallpapers/lightmode/daniel-clarke-yb-30sec-sh020-bg-paint-v021.jpg"

[widget.active_window]
anchor = true
interactive = false
title_scroll = "on_hover"

[widget.brightness]
enabled = false

[widget.media]
hide_when_no_media = true
show_progress = true

[widget.privacy]
hide_inactive = true
