[bar.default]
center = [ "active_window" ]
end = [ "tray", "media", "notifications", "volume", "bluetooth", "network", "battery", "control-center" ]
start = [ "launcher", "workspaces", "clock" ]
thickness = 30
widget_spacing = 8

[control_center.calendar]
show_week_numbers = true

[[control_center.shortcuts]]
type = "keyboard_layout"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "dark_mode"

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[location]
address = "Hamburg, Germany"

[lockscreen]
blur_intensity = 0.0
tint_intensity = 0.0
wallpaper = "/home/lilly/Sync/Wallpapers/ccc-camp.jpg"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 1141.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.0
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = false
        show_unlock_hint = false
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 112.0
    box_width = 240.0
    cx = 960.0
    cy = 80.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        center_text = true
        clock_style = "digital"
        color = "primary"
        shadow = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 176.0
    box_width = 416.0
    cx = 221.0
    cy = 1100.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "media_player"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        hide_when_no_media = true
        layout = "horizontal"
        shadow = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 0.0
    box_width = 0.0
    cx = 1877.0
    cy = 1176.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "label"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background = false
        color = "on_tertiary"
        description = "li@lly.sh"
        shadow = false
        title = ""

[notification]
history_retention_hours = 3
max_visible = 3

[osd]
position = "top_right"

    [osd.kinds]
    keyboard_backlight = false
    lock_keys = false
    media = false

[shell]
avatar_path = "/home/lilly/Sync/ProfilePictures/poly_fox.jpg"
clipboard_enabled = false
clipboard_keep_from_closed_apps = false
launch_apps_as_systemd_services = true
settings_show_advanced = true

    [shell.launcher]
    fetch_exchange_rates = false

    [shell.panel]
    open_near_click_control_center = true
    open_near_click_session = true
    session_position = "center"

    [shell.session]
    show_shortcuts = false

[theme]
builtin = "Rosé Pine"
community_palette = "Oxocarbon"
mode = "auto"
pure_black_dark = true
source = "builtin"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "helix", "qt" ]

[wallpaper]
directory = "/home/lilly/Sync/Wallpapers"

    [wallpaper.default]
    path = "/home/lilly/Sync/Wallpapers/Artstation/laurel-d-austin-tyrannosaurusinrepose.jpg"

    [wallpaper.last]
    path = "/home/lilly/Sync/Wallpapers/Artstation/laurel-d-austin-tyrannosaurusinrepose.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/lilly/Sync/Wallpapers/Artstation/laurel-d-austin-tyrannosaurusinrepose.jpg"

[widget.active_window]
interactive = false
title_scroll = "on_hover"

[widget.brightness]
enabled = false

[widget.media]
hide_when_no_media = true
show_progress = true
