# ref: https://artifacthub.io/packages/helm/traefik/traefik

# achieve some form of graceful restart by running multiple pods
priorityClassName: custom-critical
deployment:
  replicas: 2

# enable all config providers for maximum flexibility (i'm mostly using gateway API though)
providers:
  kubernetesIngress:
    enabled: true
  kubernetesCRD:
    enabled: true
  kubernetesGateway:
    enabled: false

# specify that we want a dual-stack service for handling incoming traffic
service:
  spec:
    ipFamilies: [ IPv6, IPv4 ]
    ipFamilyPolicy: RequireDualStack
    externalTrafficPolicy: Local

# configure listening ports to be the real HTTP(S) ports since we are running on a proper load-balanced service
ports:
  web:
    port: 80
  websecure:
    port: 443

# enable traefik dashboard exposition
ingressRoute:
  dashboard:
    enabled: true
